city:
  Минск # city
date: '2018-12-01'
start: '10:30'
venue:
  - Event Space # name
  - Октябрьская, 16А # address
  - http://eventspace.by/ # link
map:
  type: yandex
  center: '29.5706,53.8896'
  marker: '72.5706,53.8896'
  zoom: '16'
partners:
  - emerline
  - adform
  - epam-systems
  - html-academy
video:
  https://youtu.be/bjxjAESwejE
