language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts:
  - web-standards.ru
script: npm test
before_deploy:
    - .travis/set-up-ssh
deploy:
  provider: script
  skip_cleanup: true
  script: "./.travis/deploy"
  on:
    branch: master
    repo: web-standards-ru/new
