language: node_js
node_js:
    - "8"
script: npm run build
deploy:
    provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local-dir: public
    target-branch: gh-pages
    on:
        branch: master
