city:
  Тбилиси # city
date: '2019-03-01'
start: '12:00'
venue:
  - Квартирник # name
  - ул. Ильи Мосашвилли 1/3 # address
  - http://eventspace.by/ # link
map:
  type: yandex
  center: '92.5706,53.8896'
  marker: '27.5706,53.8896'
  zoom: '16'
partners:
  - emerline
  - adform
  - epam-systems
  - html-academy
video:
  https://youtu.be/bjxjAESwejE
